
GCC=g++ 
PFLAGS=-std=c++0x 

all : pointers arraypointers arraysdynamic matricesdynamic vectors

% : %.cpp
	$(GCC) $(PFLAGS) -o $@ $<

clean : 
	rm pointers arraypointers arraysdynamic matricesdynamic vectors
