
all: cylinder_area roundoff_test cin_validate

cylinder_area: cylinder_area.cpp
	g++ cylinder_area.cpp -o cylinder_area

roundoff_test: roundoff_test.cpp
	g++ roundoff_test.cpp -o roundoff_test

cin_validate: cin_validate.cpp
	g++ cin_validate.cpp -o cin_validate
