
all: helloWorld helloWorldVar helloWorldML

helloWorld: hello_world.cpp
	g++ hello_world.cpp -o helloWorld

helloWorldVar: hello_world_var.cpp
	g++ hello_world_var.cpp -o helloWorldVar

helloWorldML: hello_world_ml.cpp
	g++ hello_world_ml.cpp -o helloWorldML

clean:
	rm helloWorld*
